### ISSUE TITLE
`show` on `..` with negative numbers returns code that will not parse

### ISSUE THREAD

**Issue by rafaqz** [JuliaMath/IntervalSets.jl#134]
```julia
julia> -10 .. -20
-10..-20

julia> -10..-20
ERROR: syntax: invalid operator "..-" near column 6
Stacktrace:
 [1] top-level scope
   @ none:1
```
It should be:
```julia
julia> -10 .. -20
-10 .. -20
```

Then it will round-trip properly.

**Comment by dlfivefifty** [comment]
A PR on this would be lovely.

alternatively one could do ` (-10)..(-20) ` which might be clearer…

**Comment by hyrodium** [comment]
This seems an issue with Julia's parser (related: https://github.com/JuliaLang/julia/issues/32626), so I think this is not an issue with IntervalSets.jl.

**Comment by rafaqz** [comment]
That issue is 3 years old, so fixing IntervalSets is easier at this point

**Comment by hyrodium** [comment]
>so fixing IntervalSets is easier at this point .

Do you have any idea to fix this issue? (like adding method to `..-(a,b) = (a)..(-b)`?)
I'm understanding that we cannot fix this issue in IntervalSets.jl because `..-` is an invalid operator.

```julia
julia> ..
ERROR: UndefVarError: .. not defined

julia> ..-
ERROR: syntax: invalid operator "..-" near column 2
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by hyrodium** [comment]
Ah, thank you. I now understand the point. It seems better to add spaces before and after `..` just like `Complex`.

```julia
julia> complex(1.0, 3)
1.0 + 3.0im
```
