### ISSUE TITLE
Center of Rectangle?

### ISSUE THREAD

**Issue by philip-stuckey** [JuliaMath/IntervalSets.jl#144]
edit: sorry, accidentally pressed enter before writing this

Would it make sense to define `center(r::Rectangle) = center.(components(r))`? Would it work for `HyperRectangle`?

**Comment by daanhb** [comment]
May make sense for a ProductDomain (looks like an issue for DomainSets.jl, not here). In that case, yes, it would work for a HyperRectangle

**Comment by philip-stuckey** [comment]
Oops, wrong repository, sorry.

**Comment by daanhb** [comment]
No problem, how could you know - feel free to file the same comment with DomainSets.jl
