### ISSUE TITLE
How to import ..

### ISSUE THREAD

**Issue by eloualiche** [JuliaMath/IntervalSets.jl#145]
I have a quick silly question.
I cannot figure how to only import `..` for a package.

Basically I have tried `import IntervalSets: ..` but this is not quite correct.

Thanks

**Comment by hyrodium** [comment]
```
julia> import IntervalSets:(..)

julia> ..
.. (generic function with 1 method)
```

**Comment by hyrodium** [comment]
I found official documentation about this parenthesis.

>A small number of operators additionally require parentheses, e.g. `Base.:(==)`.

https://docs.julialang.org/en/v1/manual/modules/

**Comment by eloualiche** [comment]
Thank you. I missed this part of the documentation! This is helpful.
