### ISSUE TITLE
Add <, etc.

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/IntervalSets.jl#15]
I'd expect this to return true, but is not implemented:
```julia
0 ≤ 0..1
```
If this is agreed, I can go ahead and put together a pull request.

**Comment by timholy** [comment]
What would `0.5 ≤ 0..1` do?

**Comment by dlfivefifty** [comment]
I'd say false, as it's not ≤ all numbers in the interval

**Comment by hyrodium** [comment]
Note that `Set([1,2,3]) < 5` is not defined. Do we really need `<(::Real, ::Interval)`?
```julia
julia> Set([1,2,3]) < 5
ERROR: MethodError: no method matching isless(::Set{Int64}, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real) at operators.jl:186
  isless(::Real, ::Real) at operators.jl:434
  isless(::Any, ::Missing) at missing.jl:88
  ...
```

**Comment by dlfivefifty** [comment]
After 5 years I've forgotten why I created this issue. Let's just close it.
