### ISSUE TITLE
`geomean(::AbstractInterval)` is not correct

### ISSUE THREAD

**Issue by hyrodium** [JuliaMath/IntervalSets.jl#173]
```julia
julia> using IntervalSets, StatsBase

julia> a, b = 5, 10
(5, 10)

julia> geomean(a..b)  # Should be 7.3575...
7.0710678118654755

julia> geomean(range(a,b,length=10000))
7.357559595510975

julia> exp((b*log(b)-a*log(a)-b+a)/(b-a))
7.357588823428852
```

`geomean(::AbstractInterval)` was introduced in #171, but the definition `sqrt(leftendpoint(d) * rightendpoint(d))` seems not correct.

$$
\mathop{\text{GM}}[a..b]
= \exp\left(\frac{1}{b-a} \int_a^b \log(x) dx \right)
= \exp\left(\frac{b\log(b)-a\log(a)-b+a}{b-a}\right)
$$

See [Geometric mean (wikipedia)](https://en.wikipedia.org/wiki/Geometric_mean#Geometric_mean_of_a_continuous_function) for more information.

This correct definition has the following consistency with `mean(range(...))`

```julia
julia> using IntervalSets, StatsBase, Plots

julia> plot([geomean(range(a,b,length=n)) for n in 2:1000], label="geomean of evenly spaced points")

julia> hline!([exp((b*log(b)-a*log(a)-b+a)/(b-a))], label="geomean of an interval set")
```

![geomean](https://github.com/JuliaMath/IntervalSets.jl/assets/7488140/252b51df-6eef-40de-b001-9fac7987338e)

@aplavin
Where did you find the original definition in https://github.com/JuliaMath/IntervalSets.jl/pull/171/files#diff-29865909ee404f36758d3fb0d2d549a636b7c5cd4967d9855c245f59b3a0bb67R6?

**Comment by hyrodium** [comment]
I see. Thank you for the explanation.

>I don't think there is unambiguous meaning of "(geo)mean of an interval" in maths in general, so here we just choose the most pragmatic one.

I think `mean(a..b)` should be defined by $E[X], (X \sim \text{Uniform}(a,b))$. This definition can be regarded as a centroid of an interval, and it can be generalized to a non-connected subset of $\mathbb{R}$.

>Don't really understand the connection between mean/geomean of an interval and mean/geomean of a function (that you linked).

How about this comment (https://stats.stackexchange.com/a/386476)? Similarly to `mean(a..b)`, I think `geomean(a..b)` should be defined by $\exp(E[\log(X)]), (X \sim \text{Uniform}(a,b))$. The `geomean` function is owned by StatsBase.jl, so I believe we need statistics theory to add methods to this function.

>I wonder what usecases you have, where the current `geomean` definition doesn't give the expected result.

I actually don't have use cases for `geomean` for now. I just thought the inconsistent definition discussed above should not be provided from this package.

>All uses are for plotting: find the midpoint of the interval when plotted on the logscale.

Then, how about adding a new function `mean_logscale(::AbstractInterval)` instead of adding a `geomean(::AbstractInterval)` method?

**Comment by timholy** [comment]
I agree that the notion proposed by @hyrodium is the more mathematically correct one. Of course, for both `mean` and `geomean`, there's an implicit sense of measure, i.e., that we're computing, e.g.,

$$
\frac{\int x dx}{\int dx}
$$

rather than

$$
\frac{\int x w(x) dx}{\int w(x) dx}
$$

Strictly speaking that's not encoded by just knowing the endpoints of the interval, and it's not invariant to changes of coordinates, i.e., `mean(f.(a..b)) != f(mean(a..b))`.
