### ISSUE TITLE
width of integer & similar intervals

### ISSUE THREAD

**Issue by tpapp** [JuliaMath/IntervalSets.jl#21]
Currently
```julia
julia> width(Date(1980,1,1)..Date(1980,1,10))
9 days

julia> width(1..10)
9
```
which makes sense in some contexts, but in others `10` would be a better choice (eg duration of a spell represented by the interval).

I would like to initiate discussion on how to handle this. The following come to mind:

1. Encourage the user to redefine `width` with `+1` or equivalent whenever that makes sense, but don't do this automatically. *Problem*: `width(1.0..10.0) ≠ width(1..10)` if one redefines it. For `Date` and similar this would not be a problem.

2. To implement 1. more elegantly, one can define a trait, eg `Date` would have the trait `RepresentsDuration()`, `width` would test for that, and add `1` accordingly. The default would be not having this trait. *Problem*: same as above, *advantage*: user could inspect this behavior for generic types.

3. Add another generic function, eg `span`, which adds `1` whenever applicable. Again, with or without trait.

Thoughts?

**Comment by timholy** [comment]
How about `length` and define it only for `Integer` intervals?

**Comment by tpapp** [comment]
Thanks for the suggestion, see PR https://github.com/JuliaMath/IntervalSets.jl/pull/22.

**Comment by dlfivefifty** [comment]
We now have `duration`. But probably the current behaviour is wrong and duration of dates should return a date?
```julia
julia> duration(Date(1980,1,1)..Date(1980,1,10))
10

julia> duration(1..10)
10
```

**Comment by timholy** [comment]
Yes, definitely the units need to be preserved. And just to check (sorry, short on time), I think we got rid of `length`, right?

**Comment by dlfivefifty** [comment]
Yes we got rid of `length`: `length` is a notion of cardinality, not measure, so it was an abuse of terminology, and also doesn't play well with Base's assumptions on length.

If anything, the following is the most reasonable definition of `length:
```julia
length(d::AbstractInterval) = (@assert !isempty(d); ℵ₁)`
```

**Comment by hyrodium** [comment]
`length` was removed https://github.com/JuliaMath/IntervalSets.jl/issues/31, so I'll close this issue. Note that `duration` will also be removed in the future release. (#102)
