### ISSUE TITLE
`in(interval, interval)` doesn't make sense (to me)

### ISSUE THREAD

**Issue by andyferris** [JuliaMath/IntervalSets.jl#29]
Julia generally clearly seperates the concepts of containers and their elements.

It seems valid that a interval may be a subset of another interval via `issubset` but generally (scalar) elements will be `in` an interval. I feel it might be preferable to remove the `in(a::ClosedInterval, b::ClosedInterval)` method.

**Comment by timholy** [comment]
Fixed by #62.
