### ISSUE TITLE
Add range(::ClosedInterval, length=n)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/IntervalSets.jl#43]
This would be convenient to have:
```julia
range(-1..1, length=10)
```

**Comment by timholy** [comment]
Meaning, it constructs the equivalent of `range(-1, stop=1, length=10)`, right?

**Comment by myrddin89** [comment]
Following up. Is this going to implemented? I would propose to extend the interface like so:

```julia
range(i::ClosedInterval, len) = range(i, length=len)
range(i::ClosedInterval; length) = range(endpoints(i)...; length)
```

I am not sure how to deal with the `step` case. Maybe consider the interval (right)open?
Definitely it could be useful to have a uniform interface for ranges supporting also intervals.

**Comment by dlfivefifty** [comment]
If you make a PR I can merge it

**Comment by myrddin89** [comment]
Sure, will do!
