### ISSUE TITLE
Override isapprox(::Interval, ::Interval)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/IntervalSets.jl#44]
The easiest definition would be
```julia
isapprox(a::Interval, b::Interval; kwds...) = isapprox(leftendpoint(a), leftendpoint(b); kwds...) && isapprox(rightendpoint(a), rightendpoint(b); kwds...)
```
But we should probably be smarter about relative tolerance: for example, I'd expect
```julia
0..1 ≈ eps()..1
```
even though 
```julia
!(0 ≈ eps())
```

**Comment by timholy** [comment]
Could add `atol=Base.rtoldefault(max(abs(...))` and put this before `kwds` so it can be overridden.

**Comment by dlfivefifty** [comment]
I think the question is more mathematical than implementation: what should ` atol ` and ` rtol ` mean for intervals?

**Comment by timholy** [comment]
I'd argue that basing it on the maximum abs value of all endpoints is pretty well-justified mathematically given the behavior of floating point.
