### ISSUE TITLE
Rename `isopen`/`isclosed` to `isopenset`/`isclosedset`

### ISSUE THREAD

**Issue by daanhb** [JuliaMath/IntervalSets.jl#59]
The package defines both `isclosed` and `isopen` for intervals, but only `isclosed` is exported.

Using this package downstream and extending `isopen` is complicated by the fact that Base defines `isopen`, albeit with an entirely different meaning in I/O, but IntervalSets does not import it.

The solution may be to both import (from Base) and export `isopen` in IntervalSets? Or is this intentional?

**Comment by dlfivefifty** [comment]
We could import `Base.isopen`, the only reason we didn't is because it referred to a file being open. But on second thought I think its OK for functions to mean different things in different contexts.

**Comment by daanhb** [comment]
It does look odd, but the different meanings would be clearly distinguished by the type of the argument.

The concrete issue for me was that writing `import IntervalSets: isopen` in `DomainSets` yields a warning because of the existence in Base. Yet, not exporting `isopen` ourselves makes the functionality less useful. I'll make a PR.

**Comment by dlfivefifty** [comment]
Probably the best thing to do is make a PR and see if anyone comments

**Comment by timholy** [comment]
Of course you can always say `IntervalSets.isopen(s)`.

I am on the fence about whether `isopen` is a name or a concept; if it's the former, there is no harm extending the Base version. If it's the latter, then very different uses should probably be different `isopen`s (scoped by module). Does anyone know of any guidance about this?

**Comment by dlfivefifty** [comment]
I think it’s a “name”, in the same way * means both multiplication and string concatenation.

**Comment by daanhb** [comment]
Now I see that I misunderstood the situation, sorry. DomainSets was actually working as intended: it imports the `isopen` from IntervalSets and does not export it. Indeed, it is perfectly usable by qualifying with the package name `IntervalSets.isopen` or `DomainSets.isopen`.

Given that apparently I've not used this functionality in a while, it is not exactly a pressing issue to me. I tend to agree that in this case it is a name, and importing `isopen` from Base would be fairly safe. However, this may not be a general solution. It would be interesting to look for other examples.

**Comment by daanhb** [comment]
There is some discussion [here](https://discourse.julialang.org/t/extending-base-methods-with-same-name-completely-different-meaning/11082/3) in favour of keeping functions with different meanings separate, either by renaming or by scoping.

**Comment by daanhb** [comment]
More discussion [here](https://stackoverflow.com/questions/54433774/adding-a-base-function-vs-using-a-unique-function-name-in-julia) with the same conclusion.

**Comment by dlfivefifty** [comment]
Perhaps a simple solution is rename them to `isclosedset` and `isopenset`, which is more descriptive anyways.

**Comment by daanhb** [comment]
That sounds even better! Meanwhile I've hastily made a pull request to add documentation for `isopen`, it was missing. That can be ignored.

So, the three options are:
- Keep things as they are, add documentation for `IntervalSets.isopen`.
- Import and extend `isopen` from Base.
- Rename to `isclosedset` and `isopenset`.

An advantage of the latter is that it can be implemented for sets that are not actually `<:Domain{T}`, with the meaning retained in the function name.

**Comment by dlfivefifty** [comment]
Let's go with rename. it will lead to more readable code and side step the issue.

(This is by no means an endorsement of the conclusions of the discussions, which are too narrow to be "decisive". And I do think the example of `*` clearly violates this, where the same name is used for very different operations depending on the types of the arguments.)

**Comment by hyrodium** [comment]
>I think it’s a “name”, in the same way * means both multiplication and string concatenation.

>And I do think the example of * clearly violates this, where the same name is used for very different operations depending on the types of the arguments.

Both operations can be regarded as monoid operations, so I personally think this is consistent.

**Comment by hyrodium** [comment]
However, I would be happy if it would be a good practice to add methods to a function with a broad meaning name even if they are different uses than in `Base`.

**Comment by daanhb** [comment]
This seems an old issue that I forgot was still open. The associated PR was merged so I'll be closing it (though happy to discuss naming again if it remains an issue).
