### ISSUE TITLE
`OpenInterval(0,1) ⊆ OpenInterval(0,1)` returns false

### ISSUE THREAD

**Issue by hyrodium** [JuliaMath/IntervalSets.jl#61]
In mathematics, an open interval (a,b) is a subset of itself.
But the code below returns `false`.
```julia
julia> using IntervalSets

julia> OpenInterval(0,1) ⊆ OpenInterval(0,1)
false
```
I think it should return `true`, and this is because of the code below:
```julia
issubset(A::AbstractInterval, B::AbstractInterval) = ((leftendpoint(A) in B) && (rightendpoint(A) in B)) || isempty(A)
```
(from 96th line of https://github.com/JuliaMath/IntervalSets.jl/blob/master/src/IntervalSets.jl)

**Comment by dlfivefifty** [comment]
You are correct. Can you submit a PR?

**Comment by hyrodium** [comment]
Thank you for your comment. I'll try!
