### ISSUE TITLE
Validate endpoint order

### ISSUE THREAD

**Issue by omus** [JuliaMath/IntervalSets.jl#65]
Interval sets should probably enforce that the left-endpoint is less than or equal to the right-endpoint:
```julia
julia> using IntervalSets

julia> Interval(1, 3) ∩ Interval(2, 3)
2..3

julia> Interval(3, 1) ∩ Interval(2, 3)
3..1
```

**Comment by dlfivefifty** [comment]
No this is intentional: ` Interval(3,1) ` is an empty interval
