### ISSUE TITLE
in(0,1..(-1)) should return true

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/IntervalSets.jl#8]
The `in` override assumes that left and right are ordered, which may not be the case.

**Comment by timholy** [comment]
An empty set has no elements, so the result is correct.

```jl
julia> 0 ∈ 1..(-1)
false

julia> 0 ∈ 1:-1
false
```

**Comment by dlfivefifty** [comment]
Yes you are right.  I was thinking of line segment

https://en.wikipedia.org/wiki/Line_segment

I think I should rename `Interval` in ApproxFun to `Segment`.  I could use another notation than `..`, maybe `a⥛b`.

**Comment by dlfivefifty** [comment]
To be more precise: I'm thinking of _oriented_ line segment

**Comment by StefanKarpinski** [comment]
Why would it be renamed to `Segment`? The term `Interval` seems standard here.

**Comment by dlfivefifty** [comment]
According to Wikipedia and baby Rudin, an interval [a,b] is {x : a <= x <= b}.  Therefore, [1,0] would be the empty set, which is the convention used in IntervalSets.jl.  Also, if a,b are in R^2, then [a,b] is defined by Rudin to be a rectangle.

In ApproxFun, I want to interpret [1,0] as the oriented line segment from 1 to 0.  More importantly, [0,1+im] is the line segment from 0 to 1+im and [Vec(0,0),Vec(1,1)] as a line segment in R^2.  Since this usage is inconsistent with standard definitions of interval, it seems beneficial to change the name, especially if we depend on IntervalSets.jl for the a..b notation.

**Comment by StefanKarpinski** [comment]
Oh, that makes sense – I thought you were proposing that `Interval` in `IntervalSets` be renamed.
