### ISSUE TITLE
Error with TagBot

### ISSUE THREAD

**Issue by hyrodium** [JuliaMath/IntervalSets.jl#87]
The v0.5.4 was released yesterday, but the TagBot threw an error.
https://github.com/JuliaMath/IntervalSets.jl/runs/5625237461?check_suite_focus=true#step:3:42

![image](https://user-images.githubusercontent.com/7488140/159504029-1bf4f352-e773-4193-aba1-680619169483.png)

Maybe some key in this repo is invalid?

**Comment by hyrodium** [comment]
@timholy Do you have any thoughts on this?

**Comment by hyrodium** [comment]
I'm not sure, but could you try that and re-run the action?

**Comment by timholy** [comment]
https://github.com/JuliaMath/IntervalSets.jl/runs/5757587415?check_suite_focus=true

**Comment by hyrodium** [comment]
Hmm, it didn't throw errors, but says:

>No new versions to release

Maybe we should tag `v0.5.4` and release it manually. After that, we can try release `v0.6.0`.

**Comment by hyrodium** [comment]
I just released v0.5.4 now. https://github.com/JuliaMath/IntervalSets.jl/releases/tag/v0.5.4

**Comment by hyrodium** [comment]
It worked for `v0.6.0`!
https://github.com/JuliaMath/IntervalSets.jl/releases/tag/v0.6.0
