### ISSUE TITLE
Drop support for `convert(ClosedInterval,3)`?

### ISSUE THREAD

**Issue by hyrodium** [JuliaMath/IntervalSets.jl#97]
`convert(ClosedInterval,3)` is supported on the current master branch.

```julia
julia> convert(ClosedInterval,3)
3..3
```

However, I think this should not be supported like `convert(StepRange,3)`.

```julia
julia> convert(StepRange,3)
ERROR: MethodError: Cannot `convert` an object of type 
  Int64 to an object of type 
  StepRange
Closest candidates are:
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray at ~/julia/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:58
  convert(::Type{T}, ::AbstractRange) where T<:AbstractRange at ~/julia/julia-1.7.2/share/julia/base/range.jl:215
  convert(::Type{T}, ::T) where T<:AbstractArray at ~/julia/julia-1.7.2/share/julia/base/abstractarray.jl:16
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

**Comment by dlfivefifty** [comment]
I disagree. An interval satisfies the "domain interface" which means it implements `in`. In this case `Integer`s such as `3` also satisfy the domain interface. So in this sense the conversion makes sense: `x in 3` returns true iff `x in 3..3` returns true.

**Comment by hyrodium** [comment]
Okay, I have two questions:

* Should we have conversions `convert(Vector,1)` and `convert(StepRange,1)` in `Base`?
* Is it consistent with Julia documentation?
    * >since convert can be called implicitly, its methods are restricted to cases that are considered "safe" or "unsurprising".
    * https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-vs.-Construction

I personally think the answer to these is no because "domain interface" for `3` is just for convenience in iteration.

**Comment by hyrodium** [comment]
Or, is there any practical benefit for `convert(ClosedInterval,3)`?
